### ISSUE TITLE
Add VRC color profiles

### ISSUE THREAD

**Issue by erikquinn** [vZMA/ZMA#102] opened 2020-10-05 13:47 UTC
People can't see shit when their video maps are bright green, just like the a/c. We should provide a set of color profiles that makes this less awful.

**Comment by FriedrichKayak** [comment] 2020-12-09 00:16
We can make these available for import into VRC.

**Comment by FriedrichKayak** [comment] 2020-12-30 02:05
If color profiles come along with session profiles, then we should merge this with #105 .

**Comment by FriedrichKayak** [comment] 2020-12-30 02:12
Closed as duplicate of #105.

**Closed by FriedrichKayak** 2020-12-30 02:12 UTC
Labels: enhancement
